In [48]:
# Task 1 — Fetch and Validate the Response
import requests

import pandas as pd

# API endpoint
url = "https://restcountries.com/v2/all"

try:
    response = requests.get(url)

    # Print status code
    print("HTTP Status Code:", response.status_code)

    # Check if request was successful
    if response.status_code == 200:
        data = response.json()
        print("Total number of countries retrieved:", len(data))
    else:
        print("Request failed. Please check the API endpoint.")

except requests.exceptions.RequestException as e:
    print("Error occurred while making the request:", e)

HTTP Status Code: 400
Request failed. Please check the API endpoint.

In [49]:
# Task 2 — Extract and Display Key Fields

# Ensure 'data' was successfully populated from the API call
if 'data' in locals() and data is not None:
    # Create empty list to store extracted data
    countries_list = []

    # Loop through JSON response
    for country in data:
        # Adjusted parsing for restcountries.com v3.1 structure
        common_name = country.get("name", {}).get("common", "Unknown")
        population = country.get("population", 0)
        region = country.get("region", "Unknown")
        area = country.get("area", 0)

        countries_list.append({
            "common_name": common_name,
            "population": population,
            "region": region,
            "area": area
        })

    # Convert list to DataFrame
    df = pd.DataFrame(countries_list)

    # Display first 10 rows
    print("DataFrame head after extracting key fields:")
    display(df.head(10))
else:
    print("Error: 'data' was not populated from the API call. Please check the previous cell's output for issues.")
    df = pd.DataFrame() # Initialize an empty DataFrame to avoid further errors

DataFrame head after extracting key fields:

          common_name  population    region       area
0        Cook Islands       15040   Oceania      236.0
1              Guinea    14363931    Africa   245857.0
2    Christmas Island        1692   Oceania      135.0
3                Togo     8095498    Africa    56785.0
4              Taiwan    23317031      Asia    36197.0
5          Kyrgyzstan     7281800      Asia   199951.0
6            Suriname      616500  Americas   163820.0
7  Dominican Republic    10771504  Americas    48671.0
8           Guatemala    18079810  Americas   108889.0
9             Algeria    47400000    Africa  2381741.0

In [50]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 250 entries, 0 to 249
Data columns (total 4 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   common_name  250 non-null    object
 1   population   250 non-null    int64
 2   region       250 non-null    object
 3   area         250 non-null    float64
dtypes: float64(1), int64(1), object(2)
memory usage: 7.9+ KB

In [51]:
# Display summary statistics for the DataFrame
display(df.describe())

         population          area
count  2.500000e+02  2.500000e+02
mean   3.207798e+07  6.010389e+05
std    1.319655e+08  1.912575e+06
min    0.000000e+00  4.900000e-01
25%    2.233542e+05  1.194250e+03
50%    5.279123e+06  6.492950e+04
75%    2.037166e+07  3.841505e+05
max    1.417492e+09  1.709825e+07

In [52]:
import requests
import pandas as pd

# URL of the CSV file with country data
csv_url = "https://query.data.world/s/q5hthj5t7x547v6n6x7w7k7t7s5t6b"
csv_file_path = "/tmp/countries.csv"

try:
    print(f"Attempting to download CSV from: {csv_url}")
    response = requests.get(csv_url)
    response.raise_for_status() # Raise an HTTPError for bad responses (4xx or 5xx)

    with open(csv_file_path, "wb") as f:
        f.write(response.content)
    print(f"CSV downloaded successfully to {csv_file_path}")

    # Load the CSV into a DataFrame
    df_countries = pd.read_csv(csv_file_path)
    print(f"Loaded {len(df_countries)} countries from CSV.")

except requests.exceptions.RequestException as e:
    print(f"Error downloading or loading CSV: {e}")
    df_countries = pd.DataFrame() # Create an empty DataFrame in case of error

Attempting to download CSV from: https://query.data.world/s/q5hthj5t7x547v6n6x7w7k7t7s5t6b
Error downloading or loading CSV: 404 Client Error: Not Found for url: https://query.data.world/s/q5hthj5t7x547v6n6x7w7k7t7s5t6b

In [53]:
# Task 2 — Extract and Display Key Fields

# Ensure df_countries is available from the previous step
if 'df_countries' in locals() and not df_countries.empty:
    # Rename columns to match the desired output keys
    df = df_countries.rename(columns={
        "Name": "common_name",
        "Population": "population",
        "Region": "region",
        "Area": "area"
    })

    # Select only the relevant columns and display first 10 rows
    df = df[["common_name", "population", "region", "area"]]
    print("Processed DataFrame head:")
    print(df.head(10))
else:
    print("Error: 'df_countries' not found or is empty. Please ensure the CSV was loaded correctly.")
    df = pd.DataFrame() # Initialize an empty DataFrame to avoid further errors

Error: 'df_countries' not found or is empty. Please ensure the CSV was loaded correctly.

In [54]:
import requests

url = "https://restcountries.com/v3.1/all"

try:
    response = requests.get(url)
    print(f"HTTP Status Code for {url}: {response.status_code}")
    if response.status_code == 200:
        print("API seems to be working correctly.")
    else:
        print("API returned an error status code. There might be an issue with the service.")
except requests.exceptions.RequestException as e:
    print(f"Could not connect to the API: {e}")

HTTP Status Code for https://restcountries.com/v3.1/all: 400
API returned an error status code. There might be an issue with the service.

In [55]:
import requests

# API endpoint
url = "https://restcountries.com/v2/all"

try:
    response = requests.get(url)

    # Print status code
    print("HTTP Status Code:", response.status_code)

    # Check if request was successful
    if response.status_code == 200:
        data = response.json()
        print("Total number of countries retrieved:", len(data))
    else:
        print("Request failed. Please check the API endpoint.")

except requests.exceptions.RequestException as e:
    print("Error occurred while making the request:", e)

HTTP Status Code: 400
Request failed. Please check the API endpoint.

In [44]:
# Task 3 — Summarize the Data

# Region with highest total population
region_population = df.groupby("region")["population"].sum()
highest_population_region = region_population.idxmax()
highest_population_value = region_population.max()

# Country with largest area
largest_country = df.loc[df["area"].idxmax(), "common_name"]
largest_area_value = df["area"].max()

# Print results
print("Region with Highest Total Population:", highest_population_region)
print("Total Population:", highest_population_value)

print("\nCountry with Largest Area:", largest_country)
print("Area:", largest_area_value)

Region with Highest Total Population: Asia
Total Population: 4724731966

Country with Largest Area: Russia
Area: 17098246.0

In [42]:
import requests
import pandas as pd

# API endpoint for restcountries v3.1
# The API now requires specifying fields and limits to 10 fields
url = "https://restcountries.com/v3.1/all?fields=name,population,region,area"

# Headers to potentially bypass common blocking issues (e.g., User-Agent)
headers = {
    'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.110 Safari/537.3'
}

try:
    print(f"Attempting to fetch data from: {url}")
    response = requests.get(url, headers=headers)

    # Print status code
    print("HTTP Status Code:", response.status_code)

    # Check if request was successful
    if response.status_code == 200:
        data = response.json()
        print("Total number of countries retrieved:", len(data))
        print("Successfully retrieved data from restcountries.com v3.1.")
    else:
        print(f"Request failed with status code {response.status_code}.")
        print("Response content (if any):", response.text) # Print response content for debugging
        data = None # Ensure data is not defined on failure

except requests.exceptions.RequestException as e:
    print("Error occurred while making the request:", e)
    data = None

Attempting to fetch data from: https://restcountries.com/v3.1/all?fields=name,population,region,area
HTTP Status Code: 200
Total number of countries retrieved: 250
Successfully retrieved data from restcountries.com v3.1.

If the above cell successfully retrieved data (`HTTP Status Code: 200`), let's proceed to extract the key fields and create a DataFrame.

In [43]:
# Task 2 — Extract and Display Key Fields

# Ensure 'data' was successfully populated from the API call
if 'data' in locals() and data is not None:
    countries_list = []

    # Loop through JSON response
    for country in data:
        # Adjusted parsing for restcountries.com v3.1 structure
        common_name = country.get("name", {}).get("common", "Unknown")
        population = country.get("population", 0)
        region = country.get("region", "Unknown")
        area = country.get("area", 0)

        countries_list.append({
            "common_name": common_name,
            "population": population,
            "region": region,
            "area": area
        })

    # Convert list to DataFrame
    df = pd.DataFrame(countries_list)

    # Display first 10 rows
    print("DataFrame head after extracting key fields:")
    display(df.head(10))
else:
    print("Error: 'data' was not populated from the API call. Please check the previous cell's output for issues.")
    df = pd.DataFrame() # Initialize an empty DataFrame to avoid further errors

DataFrame head after extracting key fields:

          common_name  population    region       area
0        Cook Islands       15040   Oceania      236.0
1              Guinea    14363931    Africa   245857.0
2    Christmas Island        1692   Oceania      135.0
3                Togo     8095498    Africa    56785.0
4              Taiwan    23317031      Asia    36197.0
5          Kyrgyzstan     7281800      Asia   199951.0
6            Suriname      616500  Americas   163820.0
7  Dominican Republic    10771504  Americas    48671.0
8           Guatemala    18079810  Americas   108889.0
9             Algeria    47400000    Africa  2381741.0