**1.Import Libraries and Create Dataset**

In [4]:
import pandas as pd
import random

random.seed(42)

# Define data parameters
regions = ['North', 'South', 'East', 'West']
categories = ['Electronics', 'Clothing', 'Home & Garden', 'Sports', 'Books']
salespersons = ['Alice', 'Bob', 'Carol', 'David', 'Emma', 'Frank']

# Generate 200 sales transactions
data = {
    'transaction_id': range(1001, 1201),
    'region': [random.choice(regions) for _ in range(200)],
    'category': [random.choice(categories) for _ in range(200)],
    'salesperson': [random.choice(salespersons) for _ in range(200)],
    'sales_amount': [round(random.uniform(50, 5000), 2) for _ in range(200)],
    'customer_id': [random.randint(5000, 5100) for _ in range(200)]
}

df = pd.DataFrame(data)
print(df.head(10))
print(f"\nDataset shape: {df.shape}")

   transaction_id region     category salesperson  sales_amount  customer_id
0            1001  North  Electronics        Emma       4000.80         5075
1            1002  North        Books       Alice       3634.70         5084
2            1003   East  Electronics       David       4210.50         5025
3            1004  South  Electronics        Emma       4601.73         5054
4            1005  South     Clothing         Bob       4904.57         5014
5            1006  South     Clothing       Carol       2693.91         5069
6            1007  North       Sports       Alice       4539.30         5028
7            1008  North       Sports       Frank       2979.87         5082
8            1009   West       Sports       David       3331.85         5019
9            1010  North     Clothing       Alice        465.54         5034

Dataset shape: (200, 6)

**Task 1: Basic Grouping and Single Aggregations**


**1.Total Sales by Region**

groupby() - region and sales_amount two columns calculate the sum values.
region_sales.sort_values by - sales_amount column it will ascending on false satatement.(with out ascending)
display the new region_sales value.

In [9]:
region_sales = df.groupby('region')['sales_amount'].sum().reset_index()
region_sales = region_sales.sort_values(by='sales_amount', ascending=False)
print(region_sales)

  region  sales_amount
2  South     158977.36
1  North     135181.16
3   West     109383.07
0   East      95189.81

**2. Number of Transactions per Category**

Data frame in groupby - category and transaction_id to find the count values.

In [10]:
category_transaction = df.groupby('category')['transaction_id'].count().reset_index()
print(category_transaction)

        category  transaction_id
0          Books              39
1       Clothing              42
2    Electronics              45
3  Home & Garden              43
4         Sports              31

**3. Average Sales Amount per Salesperson**

Dataframe groupby - salesperson and sales_amount to find the mean values.

In [11]:
avg_salesperson_sales= df.groupby('salesperson')['sales_amount'].mean().reset_index()
print(avg_salesperson_sales)

  salesperson  sales_amount
0       Alice   1998.432273
1         Bob   2554.919063
2       Carol   2454.368571
3       David   2743.036444
4        Emma   2493.457273
5       Frank   2464.135750

**Task 2: Multi-Column Grouping and Multiple Aggregations**

**1.Total Sales by Region and Category**

Multi column have a groupby region,category,sales_amount to find the sum values.

In [12]:
region_category_sales = df.groupby(['region','category'])['sales_amount'].sum().reset_index()
print(region_category_sales)

   region       category  sales_amount
0    East          Books      20027.53
1    East       Clothing      19926.20
2    East    Electronics      22791.55
3    East  Home & Garden      15949.08
4    East         Sports      16495.45
5   North          Books      42592.53
6   North       Clothing      18959.06
7   North    Electronics      38889.84
8   North  Home & Garden      19344.48
9   North         Sports      15395.25
10  South          Books      21007.68
11  South       Clothing      50878.36
12  South    Electronics      39229.63
13  South  Home & Garden      22592.00
14  South         Sports      25269.69
15   West          Books      20359.41
16   West       Clothing      16548.81
17   West    Electronics      13553.27
18   West  Home & Garden      33069.36
19   West         Sports      25852.22

**2. Salesperson Performance Metrics**

Dataframe groupby salesperson,sales_amount and aggerication(sum,mean,max,min) this all field put together.
So,given output received from the values are sorting and sum in non ascending field.
Display the output value of saleperson_performance.

In [13]:
saleperson_performance=df.groupby('salesperson')['sales_amount'].agg(['sum','mean','max','min']).reset_index()
saleperson_performance = saleperson_performance.sort_values(by='sum', ascending=False)
print(saleperson_performance)

  salesperson        sum         mean      max     min
3       David  123436.64  2743.036444  4820.49  275.30
5       Frank   98565.43  2464.135750  4903.53  253.29
4        Emma   82284.09  2493.457273  4983.33  249.28
1         Bob   81757.41  2554.919063  4904.57  112.63
2       Carol   68722.32  2454.368571  4802.54  110.71
0       Alice   43965.51  1998.432273  4539.30  135.35

**3. Category with Maximum Total Revenue:**

Dataframe groupby category and sales_amount to find the sum values
To given the values to find the idmax vlaues.
Display the output

In [14]:
category_sales = df.groupby('category')['sales_amount'].sum()
top_category = category_sales.idxmax()
print("category with highesht revenue:",top_category)

category with highesht revenue: Electronics

**Task 3: Custom Aggregation and Complete Sales Report**

**1. Define Custom Sales Range Function**

Function of sales_range and return the values of max and min aggrecations.

In [15]:
def sales_range(x):
     return x,max() - x.min()

**2. Apply Custom Aggregation by Region**

Dataframe have groupby the region and sales_amount, aggrecation of sum,mean,min,max,sales_range to find the process

Display the output values.

In [22]:
def sales_range(x):
    return x.max() - x.min()

region_analysis = df.groupby('region')['sales_amount'].agg(['sum','mean','min','max', sales_range]
                                                           ).reset_index()
print(region_analysis)

  region        sum         mean     min      max  sales_range
0   East   95189.81  2213.716512  307.82  4758.46      4450.64
1  North  135181.16  2413.949286  110.71  4788.56      4677.85
2  South  158977.36  2789.076491  373.45  4983.33      4609.88
3   West  109383.07  2485.978864  203.60  4903.53      4699.93

**3. Final Sales Summary Report**

Dataframe groupby region,aggrecation of sales_amount to find the sum,mean and customer id field count to check the process.
Display the final report output

In [23]:
final_report = df.groupby('region').agg({
    'sales_amount': ['sum', 'mean'],
    'customer_id': 'count'
}).reset_index
print(final_report)

<bound method DataFrame.reset_index of        sales_amount              customer_id
                sum         mean       count
region
East       95189.81  2213.716512          43
North     135181.16  2413.949286          56
South     158977.36  2789.076491          57
West      109383.07  2485.978864          44>

**Multi-Level Column Explanation**

Multilevel column are find : Dataframe groupby have the column of region and aggrecation of sale_amount value of sum and mean.customer_id of the count values.

In [24]:
df.groupby('region').agg({
    'sales_amount': ['sum', 'mean'],
    'customer_id': 'count'
})

       sales_amount              customer_id
                sum         mean       count
region
East       95189.81  2213.716512          43
North     135181.16  2413.949286          56
South     158977.36  2789.076491          57
West      109383.07  2485.978864          44

Dataframe groupby of region and sales_amount column to find the sum values.

In [25]:
df.groupby('region')['sales_amount'].sum()

region
East      95189.81
North    135181.16
South    158977.36
West     109383.07
Name: sales_amount, dtype: float64