**Helathcare Data Cleaning using Pandas**

**Import Libraries of Numpy and Pandas**

In [21]:
import numpy as np
import pandas as pd

**Create the DataFrame**

Create and show the DataFrame of Table format.

In [22]:
import pandas as pd
import numpy as np

data = {
    'patient_id': [101, 102, 103, 104, 105, 106, 107, 108, 109, 110,
                   111, 112, 113, 114, 115, 101, 107, 118, 119, 120],
    'age': ['25', '34', None, '45', '29', None, '38', '52', '27', '41',
            '33', 'unknown', '48', '26', '35', '25', '38', '31', None, '44'],
    'weight': ['70', '65', '80', None, '75', None, '68', '90', '72', '85',
               '78', None, '82', '69', 'N/A', '70', '68', '74', None, '88'],
    'blood_pressure': [120, 130, None, 140, 125, None, 135, None, 118, 145,
                      128, None, 138, 122, None, 120, 135, 126, None, 142],
    'medication': ['Aspirin', 'Metformin', 'Lisinopril', None, 'Aspirin',
                   'Metformin', 'Lisinopril', 'Aspirin', None, 'Metformin',
                   'Lisinopril', 'Aspirin', None, 'Metformin', 'Aspirin',
                   'Aspirin', 'Lisinopril', 'Metformin', 'Aspirin', None],
    'insurance_provider': ['Blue Cross', 'Aetna', 'Cigna', 'UnitedHealth', None,
                          'Blue Cross', 'Aetna', 'Cigna', 'UnitedHealth', 'Blue Cross',
                          'Aetna', None, 'UnitedHealth', 'Blue Cross', 'Aetna',
                          'Blue Cross', 'Aetna', 'Cigna', 'UnitedHealth', None]
}

df = pd.DataFrame(data)
df

    patient_id      age weight  blood_pressure  medication insurance_provider
0          101       25     70           120.0     Aspirin         Blue Cross
1          102       34     65           130.0   Metformin              Aetna
2          103     None     80             NaN  Lisinopril              Cigna
3          104       45   None           140.0        None       UnitedHealth
4          105       29     75           125.0     Aspirin               None
5          106     None   None             NaN   Metformin         Blue Cross
6          107       38     68           135.0  Lisinopril              Aetna
7          108       52     90             NaN     Aspirin              Cigna
8          109       27     72           118.0        None       UnitedHealth
9          110       41     85           145.0   Metformin         Blue Cross
10         111       33     78           128.0  Lisinopril              Aetna
11         112  unknown   None             NaN     Aspirin               None
12         113       48     82           138.0        None       UnitedHealth
13         114       26     69           122.0   Metformin         Blue Cross
14         115       35    N/A             NaN     Aspirin              Aetna
15         101       25     70           120.0     Aspirin         Blue Cross
16         107       38     68           135.0  Lisinopril              Aetna
17         118       31     74           126.0   Metformin              Cigna
18         119     None   None             NaN     Aspirin       UnitedHealth
19         120       44     88           142.0        None               None

**Task 1 - Inspect the Data**

**1.Data Types and Non-Null Values**

DataFrame information details check an given output.
Output have:
**Range of index : **20 entries (0 to 19)
**Data columns :** Total 6 columns
Column title(patient_id,age,weight,blood_pressure,medication,innsurnace_provider)
**Non-null count :** (patient_id = 20 non-null,age = 17 non-null,weight = 16 non-null,blood_pressure = 14 non-null,medication = 16 non-null,insurnace_provider = 17 non-null)
**Dtype :** (patient_id = int64,age = object,weight = object, blood_pressure=float64, medication = object, insurance = object)
dtypes count : float64(1),int64(1),object(4)
memory usage : 1.1+ KB taken the memory space creation of table

In [23]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 6 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   patient_id          20 non-null     int64
 1   age                 17 non-null     object
 2   weight              16 non-null     object
 3   blood_pressure      14 non-null     float64
 4   medication          16 non-null     object
 5   insurance_provider  17 non-null     object
dtypes: float64(1), int64(1), object(4)
memory usage: 1.1+ KB

**2.Count Missing Values**

DataFrame null value count calculate to below steps.SUM() keyword is using calculate the sum values.

In [24]:
df.isnull().sum()

patient_id            0
age                   3
weight                4
blood_pressure        6
medication            4
insurance_provider    3
dtype: int64

**3.Percentage of Missing Values**

Calcualte the Missing values to find the overall missing value percentage.

In [25]:
missing_percentage = (df.isnull().sum() / len(df)) * 100
missing_percentage

patient_id             0.0
age                   15.0
weight                20.0
blood_pressure        30.0
medication            20.0
insurance_provider    15.0
dtype: float64

**4. Count Duplicate Rows**

Use df.duplicated().sum() to count duplicate rows.To Find the Duplicated rows count.
(np.int64(2))

In [26]:
df.duplicated().sum()

np.int64(2)

**Task 2 - Data Type Conversion**

**1. Convert Age to Numeric**

Convert age column to numeric using pd.to_numeric(df['age'], errors='coerce')

Convert age column datatype object into numeric format of datatype is(float64).

In [27]:
df['age'] = pd.to_numeric(df['age'], errors='coerce')
df

    patient_id   age weight  blood_pressure  medication insurance_provider
0          101  25.0     70           120.0     Aspirin         Blue Cross
1          102  34.0     65           130.0   Metformin              Aetna
2          103   NaN     80             NaN  Lisinopril              Cigna
3          104  45.0   None           140.0        None       UnitedHealth
4          105  29.0     75           125.0     Aspirin               None
5          106   NaN   None             NaN   Metformin         Blue Cross
6          107  38.0     68           135.0  Lisinopril              Aetna
7          108  52.0     90             NaN     Aspirin              Cigna
8          109  27.0     72           118.0        None       UnitedHealth
9          110  41.0     85           145.0   Metformin         Blue Cross
10         111  33.0     78           128.0  Lisinopril              Aetna
11         112   NaN   None             NaN     Aspirin               None
12         113  48.0     82           138.0        None       UnitedHealth
13         114  26.0     69           122.0   Metformin         Blue Cross
14         115  35.0    N/A             NaN     Aspirin              Aetna
15         101  25.0     70           120.0     Aspirin         Blue Cross
16         107  38.0     68           135.0  Lisinopril              Aetna
17         118  31.0     74           126.0   Metformin              Cigna
18         119   NaN   None             NaN     Aspirin       UnitedHealth
19         120  44.0     88           142.0        None               None

**2.Convert Weight to Numeric**

Convert weight column to numeric using
pd.to_numeric(df['weight'], errors='coerce')

Convert weight column datatype object into numeric format of datatype is(float64).

In [28]:
df['weight'] = pd.to_numeric(df['weight'],errors='coerce')
df

    patient_id   age  weight  blood_pressure  medication insurance_provider
0          101  25.0    70.0           120.0     Aspirin         Blue Cross
1          102  34.0    65.0           130.0   Metformin              Aetna
2          103   NaN    80.0             NaN  Lisinopril              Cigna
3          104  45.0     NaN           140.0        None       UnitedHealth
4          105  29.0    75.0           125.0     Aspirin               None
5          106   NaN     NaN             NaN   Metformin         Blue Cross
6          107  38.0    68.0           135.0  Lisinopril              Aetna
7          108  52.0    90.0             NaN     Aspirin              Cigna
8          109  27.0    72.0           118.0        None       UnitedHealth
9          110  41.0    85.0           145.0   Metformin         Blue Cross
10         111  33.0    78.0           128.0  Lisinopril              Aetna
11         112   NaN     NaN             NaN     Aspirin               None
12         113  48.0    82.0           138.0        None       UnitedHealth
13         114  26.0    69.0           122.0   Metformin         Blue Cross
14         115  35.0     NaN             NaN     Aspirin              Aetna
15         101  25.0    70.0           120.0     Aspirin         Blue Cross
16         107  38.0    68.0           135.0  Lisinopril              Aetna
17         118  31.0    74.0           126.0   Metformin              Cigna
18         119   NaN     NaN             NaN     Aspirin       UnitedHealth
19         120  44.0    88.0           142.0        None               None

3.**Check New Missing Values Created**

Check how many NEW missing values were created after conversion

Age column 11th row is unknown before the conversion and after the conversion it would be change null value count added on the list

Weight column 14th row is NaN before the conversion and after the conversion it would be change null value count added on the list

Age column null value total count is 4.
Weight column null value total count is 5.

In [29]:
df[['age','weight']].isnull().sum()

age       4
weight    5
dtype: int64

4.**Convert insurance_provider to category**

Convert insurance_provider to category type using astype('category')

Convert insurance_provider column as datatype object into category format of datatype is(category).

In [30]:
df['insurance_provider']= df['insurance_provider'].astype('category')
df['insurance_provider'].info()
df

<class 'pandas.core.series.Series'>
RangeIndex: 20 entries, 0 to 19
Series name: insurance_provider
Non-Null Count  Dtype
--------------  -----
17 non-null     category
dtypes: category(1)
memory usage: 356.0 bytes

    patient_id   age  weight  blood_pressure  medication insurance_provider
0          101  25.0    70.0           120.0     Aspirin         Blue Cross
1          102  34.0    65.0           130.0   Metformin              Aetna
2          103   NaN    80.0             NaN  Lisinopril              Cigna
3          104  45.0     NaN           140.0        None       UnitedHealth
4          105  29.0    75.0           125.0     Aspirin                NaN
5          106   NaN     NaN             NaN   Metformin         Blue Cross
6          107  38.0    68.0           135.0  Lisinopril              Aetna
7          108  52.0    90.0             NaN     Aspirin              Cigna
8          109  27.0    72.0           118.0        None       UnitedHealth
9          110  41.0    85.0           145.0   Metformin         Blue Cross
10         111  33.0    78.0           128.0  Lisinopril              Aetna
11         112   NaN     NaN             NaN     Aspirin                NaN
12         113  48.0    82.0           138.0        None       UnitedHealth
13         114  26.0    69.0           122.0   Metformin         Blue Cross
14         115  35.0     NaN             NaN     Aspirin              Aetna
15         101  25.0    70.0           120.0     Aspirin         Blue Cross
16         107  38.0    68.0           135.0  Lisinopril              Aetna
17         118  31.0    74.0           126.0   Metformin              Cigna
18         119   NaN     NaN             NaN     Aspirin       UnitedHealth
19         120  44.0    88.0           142.0        None                NaN

5.**Verify Data Types**

Use df.dtypes to verify all conversions

**Coversion datatypes mention here:**

age - object - float64,
weight - object - float64,
insurnce_provider - object - category

**Non-conversion datatypes mention here:**
patient_id - int64,
blood_pressure - float64,
medication - object,

In [31]:
df.dtypes

patient_id               int64
age                    float64
weight                 float64
blood_pressure         float64
medication              object
insurance_provider    category
dtype: object

**Task 3: Handle Missing Values**
age: Fill with median using fillna(df['age'].median())

**1.Age :**
Handle Missing values  fill with age is median method.Median is the middle value in sorted dataset.Four Null values have filled.

In [32]:
df['age'].fillna(df['age'].median(), inplace=True)
df

/tmp/ipykernel_494/3695359650.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['age'].fillna(df['age'].median(), inplace=True)

    patient_id   age  weight  blood_pressure  medication insurance_provider
0          101  25.0    70.0           120.0     Aspirin         Blue Cross
1          102  34.0    65.0           130.0   Metformin              Aetna
2          103  34.5    80.0             NaN  Lisinopril              Cigna
3          104  45.0     NaN           140.0        None       UnitedHealth
4          105  29.0    75.0           125.0     Aspirin                NaN
5          106  34.5     NaN             NaN   Metformin         Blue Cross
6          107  38.0    68.0           135.0  Lisinopril              Aetna
7          108  52.0    90.0             NaN     Aspirin              Cigna
8          109  27.0    72.0           118.0        None       UnitedHealth
9          110  41.0    85.0           145.0   Metformin         Blue Cross
10         111  33.0    78.0           128.0  Lisinopril              Aetna
11         112  34.5     NaN             NaN     Aspirin                NaN
12         113  48.0    82.0           138.0        None       UnitedHealth
13         114  26.0    69.0           122.0   Metformin         Blue Cross
14         115  35.0     NaN             NaN     Aspirin              Aetna
15         101  25.0    70.0           120.0     Aspirin         Blue Cross
16         107  38.0    68.0           135.0  Lisinopril              Aetna
17         118  31.0    74.0           126.0   Metformin              Cigna
18         119  34.5     NaN             NaN     Aspirin       UnitedHealth
19         120  44.0    88.0           142.0        None                NaN

2.**Fill Weight with Median**

Handle Missing values  fill with weight is median method.Median is the middle value in sorted dataset.Five Null values have filled.

In [33]:
df['weight'].fillna(df['weight'].median(), inplace=True)
df

/tmp/ipykernel_494/277608998.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['weight'].fillna(df['weight'].median(), inplace=True)

    patient_id   age  weight  blood_pressure  medication insurance_provider
0          101  25.0    70.0           120.0     Aspirin         Blue Cross
1          102  34.0    65.0           130.0   Metformin              Aetna
2          103  34.5    80.0             NaN  Lisinopril              Cigna
3          104  45.0    74.0           140.0        None       UnitedHealth
4          105  29.0    75.0           125.0     Aspirin                NaN
5          106  34.5    74.0             NaN   Metformin         Blue Cross
6          107  38.0    68.0           135.0  Lisinopril              Aetna
7          108  52.0    90.0             NaN     Aspirin              Cigna
8          109  27.0    72.0           118.0        None       UnitedHealth
9          110  41.0    85.0           145.0   Metformin         Blue Cross
10         111  33.0    78.0           128.0  Lisinopril              Aetna
11         112  34.5    74.0             NaN     Aspirin                NaN
12         113  48.0    82.0           138.0        None       UnitedHealth
13         114  26.0    69.0           122.0   Metformin         Blue Cross
14         115  35.0    74.0             NaN     Aspirin              Aetna
15         101  25.0    70.0           120.0     Aspirin         Blue Cross
16         107  38.0    68.0           135.0  Lisinopril              Aetna
17         118  31.0    74.0           126.0   Metformin              Cigna
18         119  34.5    74.0             NaN     Aspirin       UnitedHealth
19         120  44.0    88.0           142.0        None                NaN

3.**Fill Blood Pressure with Median**

Handle Missing values fill with blood_presure is median method.Median is the middle value in sorted dataset.Six Null values have filled.

In [34]:
df['blood_pressure'].fillna(df['blood_pressure'].median(), inplace=True)
df

/tmp/ipykernel_494/2295817409.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['blood_pressure'].fillna(df['blood_pressure'].median(), inplace=True)

    patient_id   age  weight  blood_pressure  medication insurance_provider
0          101  25.0    70.0           120.0     Aspirin         Blue Cross
1          102  34.0    65.0           130.0   Metformin              Aetna
2          103  34.5    80.0           129.0  Lisinopril              Cigna
3          104  45.0    74.0           140.0        None       UnitedHealth
4          105  29.0    75.0           125.0     Aspirin                NaN
5          106  34.5    74.0           129.0   Metformin         Blue Cross
6          107  38.0    68.0           135.0  Lisinopril              Aetna
7          108  52.0    90.0           129.0     Aspirin              Cigna
8          109  27.0    72.0           118.0        None       UnitedHealth
9          110  41.0    85.0           145.0   Metformin         Blue Cross
10         111  33.0    78.0           128.0  Lisinopril              Aetna
11         112  34.5    74.0           129.0     Aspirin                NaN
12         113  48.0    82.0           138.0        None       UnitedHealth
13         114  26.0    69.0           122.0   Metformin         Blue Cross
14         115  35.0    74.0           129.0     Aspirin              Aetna
15         101  25.0    70.0           120.0     Aspirin         Blue Cross
16         107  38.0    68.0           135.0  Lisinopril              Aetna
17         118  31.0    74.0           126.0   Metformin              Cigna
18         119  34.5    74.0           129.0     Aspirin       UnitedHealth
19         120  44.0    88.0           142.0        None                NaN

4.**Fill Medication with Mode**

Handle Missing values fill with medication is mode method.Mode is the mode with index value what are assign on that result are append of all null area to be replaced.(mode(0))-Aspirin.Six Null values have filled.

In [35]:
df['medication'].fillna(df['medication'].mode()[0], inplace=True)
df

/tmp/ipykernel_494/3601773442.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['medication'].fillna(df['medication'].mode()[0], inplace=True)

    patient_id   age  weight  blood_pressure  medication insurance_provider
0          101  25.0    70.0           120.0     Aspirin         Blue Cross
1          102  34.0    65.0           130.0   Metformin              Aetna
2          103  34.5    80.0           129.0  Lisinopril              Cigna
3          104  45.0    74.0           140.0     Aspirin       UnitedHealth
4          105  29.0    75.0           125.0     Aspirin                NaN
5          106  34.5    74.0           129.0   Metformin         Blue Cross
6          107  38.0    68.0           135.0  Lisinopril              Aetna
7          108  52.0    90.0           129.0     Aspirin              Cigna
8          109  27.0    72.0           118.0     Aspirin       UnitedHealth
9          110  41.0    85.0           145.0   Metformin         Blue Cross
10         111  33.0    78.0           128.0  Lisinopril              Aetna
11         112  34.5    74.0           129.0     Aspirin                NaN
12         113  48.0    82.0           138.0     Aspirin       UnitedHealth
13         114  26.0    69.0           122.0   Metformin         Blue Cross
14         115  35.0    74.0           129.0     Aspirin              Aetna
15         101  25.0    70.0           120.0     Aspirin         Blue Cross
16         107  38.0    68.0           135.0  Lisinopril              Aetna
17         118  31.0    74.0           126.0   Metformin              Cigna
18         119  34.5    74.0           129.0     Aspirin       UnitedHealth
19         120  44.0    88.0           142.0     Aspirin                NaN

5.**Fill insurance Provider with "Unknown"**

insurance_provider: Fill with constant value 'Unknown'
Already we have insurance_provider data type is change categories.so first insurance_provider added categories and
Filled with 'Unknown' changes of the field of None.(df['insurance_provider'].fillna('Unknown', inplace=True))

In [36]:
df['insurance_provider'] = df['insurance_provider'].cat.add_categories('Unknown')
df['insurance_provider'].fillna('Unknown', inplace=True)
df

/tmp/ipykernel_494/3024145130.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['insurance_provider'].fillna('Unknown', inplace=True)

    patient_id   age  weight  blood_pressure  medication insurance_provider
0          101  25.0    70.0           120.0     Aspirin         Blue Cross
1          102  34.0    65.0           130.0   Metformin              Aetna
2          103  34.5    80.0           129.0  Lisinopril              Cigna
3          104  45.0    74.0           140.0     Aspirin       UnitedHealth
4          105  29.0    75.0           125.0     Aspirin            Unknown
5          106  34.5    74.0           129.0   Metformin         Blue Cross
6          107  38.0    68.0           135.0  Lisinopril              Aetna
7          108  52.0    90.0           129.0     Aspirin              Cigna
8          109  27.0    72.0           118.0     Aspirin       UnitedHealth
9          110  41.0    85.0           145.0   Metformin         Blue Cross
10         111  33.0    78.0           128.0  Lisinopril              Aetna
11         112  34.5    74.0           129.0     Aspirin            Unknown
12         113  48.0    82.0           138.0     Aspirin       UnitedHealth
13         114  26.0    69.0           122.0   Metformin         Blue Cross
14         115  35.0    74.0           129.0     Aspirin              Aetna
15         101  25.0    70.0           120.0     Aspirin         Blue Cross
16         107  38.0    68.0           135.0  Lisinopril              Aetna
17         118  31.0    74.0           126.0   Metformin              Cigna
18         119  34.5    74.0           129.0     Aspirin       UnitedHealth
19         120  44.0    88.0           142.0     Aspirin            Unknown

**Verify Missing Values Removed**

All null values are replaced.Again once check null value of total count.Below process null values counts are Zero.

In [37]:
df.isnull().sum()

patient_id            0
age                   0
weight                0
blood_pressure        0
medication            0
insurance_provider    0
dtype: int64

**Task 4 - Handle Duplicates **

1.**View Duplicates Rows**
In this Process we will check duplicated row list.

In [38]:
df[df.duplicated(keep=False)]

    patient_id   age  weight  blood_pressure  medication insurance_provider
0          101  25.0    70.0           120.0     Aspirin         Blue Cross
6          107  38.0    68.0           135.0  Lisinopril              Aetna
15         101  25.0    70.0           120.0     Aspirin         Blue Cross
16         107  38.0    68.0           135.0  Lisinopril              Aetna

2.**Identify Duplicates by patient_id**

Identify with only patient_id column.It Two duplicated are traceout and get the result.Its only find the patient_id column.

In [39]:
df.duplicated(subset=['patient_id']).sum()

np.int64(2)

3.**Shape Before Removing Duplicates**

Once we are removing duplicates before it will get shape of dataframe checked.Twenty rows and six columns(20,6).

In [40]:
print("Shape before removing duplicates:",df.shape)

Shape before removing duplicates: (20, 6)

3.**Remove Duplicates**

Data frame have patient column keep first duplicates will remove and after continous values are will be worked.After the 15 and 16 row will be removed of below code block.

In [41]:
df=df.drop_duplicates(subset=['patient_id'], keep='first')
df

    patient_id   age  weight  blood_pressure  medication insurance_provider
0          101  25.0    70.0           120.0     Aspirin         Blue Cross
1          102  34.0    65.0           130.0   Metformin              Aetna
2          103  34.5    80.0           129.0  Lisinopril              Cigna
3          104  45.0    74.0           140.0     Aspirin       UnitedHealth
4          105  29.0    75.0           125.0     Aspirin            Unknown
5          106  34.5    74.0           129.0   Metformin         Blue Cross
6          107  38.0    68.0           135.0  Lisinopril              Aetna
7          108  52.0    90.0           129.0     Aspirin              Cigna
8          109  27.0    72.0           118.0     Aspirin       UnitedHealth
9          110  41.0    85.0           145.0   Metformin         Blue Cross
10         111  33.0    78.0           128.0  Lisinopril              Aetna
11         112  34.5    74.0           129.0     Aspirin            Unknown
12         113  48.0    82.0           138.0     Aspirin       UnitedHealth
13         114  26.0    69.0           122.0   Metformin         Blue Cross
14         115  35.0    74.0           129.0     Aspirin              Aetna
17         118  31.0    74.0           126.0   Metformin              Cigna
18         119  34.5    74.0           129.0     Aspirin       UnitedHealth
19         120  44.0    88.0           142.0     Aspirin            Unknown

4.**Shape After Removing Duplicates**

To chcek after the removing duplicates,find the shape.It will get the result is 18 rows and 6 column.

In [42]:
print("Shape after removing duplicates:",df.shape)

Shape after removing duplicates: (18, 6)

**Task 5 - Complete Workflow with Verification**

1.**Reload Dataframe**
Reload the previous or first dataframe.

In [43]:
df=pd.DataFrame(data)
df_clean=df.copy()
df

    patient_id      age weight  blood_pressure  medication insurance_provider
0          101       25     70           120.0     Aspirin         Blue Cross
1          102       34     65           130.0   Metformin              Aetna
2          103     None     80             NaN  Lisinopril              Cigna
3          104       45   None           140.0        None       UnitedHealth
4          105       29     75           125.0     Aspirin               None
5          106     None   None             NaN   Metformin         Blue Cross
6          107       38     68           135.0  Lisinopril              Aetna
7          108       52     90             NaN     Aspirin              Cigna
8          109       27     72           118.0        None       UnitedHealth
9          110       41     85           145.0   Metformin         Blue Cross
10         111       33     78           128.0  Lisinopril              Aetna
11         112  unknown   None             NaN     Aspirin               None
12         113       48     82           138.0        None       UnitedHealth
13         114       26     69           122.0   Metformin         Blue Cross
14         115       35    N/A             NaN     Aspirin              Aetna
15         101       25     70           120.0     Aspirin         Blue Cross
16         107       38     68           135.0  Lisinopril              Aetna
17         118       31     74           126.0   Metformin              Cigna
18         119     None   None             NaN     Aspirin       UnitedHealth
19         120       44     88           142.0        None               None

2.**Shape before Cleaning**

In [44]:
shape_before = df_clean.shape

3.**Missing Values Before**

Missing Values before once check the process

In [79]:
missing_before = df_clean.isnull().sum()
print("Missing values before cleaning:")
print(missing_before)

Missing values before cleaning:
patient_id            0
age                   0
weight                0
blood_pressure        0
medication            0
insurance_provider    0
dtype: int64

4.**Duplicate Before Cleaning**

Duplicate rows cleaning process.

In [52]:
duplicates_before = df_clean.duplicated().sum()
print("Number of duplicates before cleaning:", duplicates_before)

Number of duplicates before cleaning: 2

5.**Data Type Before Cleaning**

 Data types check before cleaning process run here

In [56]:
types_before =df_clean.dtypes
print("Data types before cleaning:")
print(types_before)

Data types before cleaning:
patient_id              int64
age                    object
weight                 object
blood_pressure        float64
medication             object
insurance_provider     object
dtype: object

2.**Perform ALL cleaning steps in order: types → missing values → duplicates**

**Step 1 - Convert Data Types**
age,Weight,insurance_provider all data types converted here

In [58]:
df_clean['age']=pd.to_numeric(df_clean['age'], errors='coerce')
df_clean['weight']=pd.to_numeric(df_clean['weight'], errors='coerce')
df_clean['insurance_provider']=df_clean['insurance_provider'].astype('category')
print("Data types after cleaning:")
print(df_clean.dtypes)

Data types after cleaning:
patient_id               int64
age                    float64
weight                 float64
blood_pressure         float64
medication              object
insurance_provider    category
dtype: object

**Step 2 - Handle Missing Values**

Handle missing value to check and clean the process here

In [ ]:
df_clean['age'].fillna(df_clean['age'].median(), inplace=True)
df_clean['weight'].fillna(df_clean['weight'].median(), inplace=True)
df_clean['blood_pressure'].fillna(df_clean['blood_pressure'].median(), inplace=True)
df_clean['medication'].fillna(df_clean['medication'].mode()[0], inplace=True)

# Add 'Unknown' as a category before filling NaN values
df_clean['insurance_provider'] = (df_clean['insurance_provider'].cat.add_categories('Unknown'))
df_clean['insurance_provider'].fillna('Unknown', inplace=True)

In [70]:
df_clean.isnull().sum()

patient_id            0
age                   0
weight                0
blood_pressure        0
medication            0
insurance_provider    0
dtype: int64

**Step 3 - Remove Duplicates**

Duplicates entries are removed on this process

In [71]:
df_clean= df_clean.drop_duplicates(subset=['patient_id'], keep='first')

3.**Verification Report**

**Shape after cleaning **

Shape after Cleaning process done here.

In [73]:
shape_after = df_clean.shape
print("Shape after cleaning:")
print(shape_after)

Shape after cleaning:
(18, 6)

**Missing Values After**
Missing Values after cleaning process done here.

In [74]:
missing_after = df_clean.isnull().sum()
print("Missing values after cleaning:")
print(missing_after)

Missing values after cleaning:
patient_id            0
age                   0
weight                0
blood_pressure        0
medication            0
insurance_provider    0
dtype: int64

**Duplicates After**

Duplicates after cleaning process done here.

In [75]:
duplicates_after= df_clean.duplicated().sum()
print("Number of duplicates after cleaning:", duplicates_after)

Number of duplicates after cleaning: 0

**Data Types After**

Data types after cleaning process done here.

In [78]:
types_after = df_clean.dtypes
print("Data types after cleaning:")
print(types_after)

Data types after cleaning:
patient_id               int64
age                    float64
weight                 float64
blood_pressure         float64
medication              object
insurance_provider    category
dtype: object

**Final Report**

Print of All process the before and after cleaning work done here.

In [77]:
print("-----VERIFICATION REPORT-----")

print("\nShape before cleaning:")
print(shape_before)

print("\nShape after cleaning:")
print(shape_after)

print("\nMissing values before cleaning:")
print(missing_before)

print("\nMissing values after cleaning:")
print(missing_after)

print("\nNumber of duplicates before cleaning:", duplicates_before)
print("Number of duplicates after cleaning:", duplicates_after)

print("\nData types before cleaning:")
print(types_before)

print("\nData types after cleaning:")
print(types_after)

-----VERIFICATION REPORT-----

Shape before cleaning:
(20, 6)

Shape after cleaning:
(18, 6)

Missing values before cleaning:
patient_id            0
age                   3
weight                4
blood_pressure        6
medication            4
insurance_provider    3
dtype: int64

Missing values after cleaning:
patient_id            0
age                   0
weight                0
blood_pressure        0
medication            0
insurance_provider    0
dtype: int64

Number of duplicates before cleaning: 2
Number of duplicates after cleaning: 0

Data types before cleaning:
patient_id              int64
age                    object
weight                 object
blood_pressure        float64
medication             object
insurance_provider     object
dtype: object

Data types after cleaning:
patient_id               int64
age                    float64
weight                 float64
blood_pressure         float64
medication              object
insurance_provider    category
dtype: object